"""Lightweight perception helpers for AI modules."""

from __future__ import annotations

from typing import TYPE_CHECKING, List, Tuple

import numpy as np
import polars as pl
import structlog

from game.world.los import line_of_sight

if TYPE_CHECKING:  # pragma: no cover - type checking only
    from polars import series
    from game.game_state import GameState

log = structlog.get_logger()


def _apply_event(
    map_arr: np.ndarray, x: int, y: int, intensity: float, radius: int, game_map
) -> None:
    """Helper to add an event with radial falloff to a map."""
    for dx in range(-radius, radius + 1):
        for dy in range(-radius, radius + 1):
            tx, ty = x + dx, y + dy
            if not game_map.in_bounds(tx, ty):
                continue
            dist = abs(dx) + abs(dy)
            value = max(intensity - dist, 0)
            if value > 0:
                map_arr[ty, tx] += value


def gather_perception(
    game_state: "GameState",
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Generate perception maps used by AI systems.

    Noise and scent layers are stored on ``GameMap`` and decayed every call
    before new events are applied.  Noise is generated by movement and other
    discrete actions whereas scent is produced by entities lingering in
    locations.  Line-of-sight simply reuses the visibility grid maintained by
    ``GameState.update_fov``.
    """

    game_map = game_state.game_map

    # Decay existing perception layers
    game_map.noise_map *= 0.6  # noise fades quickly
    game_map.scent_map *= 0.9  # scent lingers longer

    # Apply queued noise events
    for x, y, intensity in getattr(game_state, "noise_events", []):
        _apply_event(game_map.noise_map, x, y, intensity, radius=2, game_map=game_map)

    # Apply queued scent events
    for x, y, intensity in getattr(game_state, "scent_events", []):
        _apply_event(game_map.scent_map, x, y, intensity, radius=4, game_map=game_map)

    # Clear processed events
    if hasattr(game_state, "noise_events"):
        game_state.noise_events.clear()
    if hasattr(game_state, "scent_events"):
        game_state.scent_events.clear()

    noise_map = game_map.noise_map.copy()
    scent_map = game_map.scent_map.copy()
    # LOS uses the latest visibility grid populated by GameState.update_fov
    los_map = game_map.visible.copy()
    log.debug("Perception maps generated", shape=noise_map.shape)
    return noise_map, scent_map, los_map


def find_visible_enemies(
    entity_row: "series",
    game_state: "GameState",
    los_map: np.ndarray,
) -> List["series"]:
    """Return a list of enemies visible to ``entity_row``.

    Entities are considered enemies if they belong to a different faction.
    Visibility is determined using both the provided ``los_map`` and a
    line-of-sight check against the game map's transparency grid.
    """

    ex, ey = entity_row.get("x"), entity_row.get("y")
    faction = entity_row.get("faction")
    game_map = game_state.game_map
    enemies: List["series"] = []

    if ex is None or ey is None:
        return enemies

    filter_expr = pl.col("is_active") is True
    if faction is not None:
        filter_expr &= pl.col("faction") != faction
    enemy_df = game_state.entity_registry.entities_df.filter(filter_expr)
    enemy_rows = {
        int(row["entity_id"]): row for row in enemy_df.iter_rows(named=True)
    }

    vision_range = int(entity_row.get("vision_range") or game_state.fov_radius)
    spatial_index = getattr(game_state, "spatial_index", None)
    nearby = None
    if spatial_index is not None and hasattr(spatial_index, "query_radius"):
        nearby = spatial_index.query_radius((int(ex), int(ey)), vision_range)

    candidates = nearby if nearby is not None else enemy_rows.values()
    for other in candidates:
        if isinstance(other, dict):
            other_row = other
            ox, oy = other_row.get("x"), other_row.get("y")
            other_id = other_row.get("entity_id")
        else:
            other_id, ox, oy = other
            other_row = enemy_rows.get(int(other_id))
            if other_row is None:
                continue
        if other_id == entity_row.get("entity_id"):
            continue
        if ox is None or oy is None:
            continue
        if not game_map.in_bounds(int(ox), int(oy)):
            continue
        if not los_map[int(oy), int(ox)]:
            continue
        if line_of_sight(int(ex), int(ey), int(ox), int(oy), game_map.transparent):
            enemies.append(other_row)

    log.debug(
        "Visible enemies located",
        entity_id=entity_row.get("entity_id"),
        count=len(enemies),
    )
    return enemies


__all__ = ["gather_perception", "find_visible_enemies"]
