# Dungeon/processor.py

from typing import Any

import math

import numpy as np
import polars as pl

# --- Constants (Ensure these are consistent with shaper.py if needed) ---
GRID_RESOLUTION = 1.0  # meters per grid cell

# --- (Heuristic Thresholds are NO LONGER NEEDED here) ---


def process_backbone_graph(
    backbone_data: dict[str, Any],
) -> tuple[list[dict[str, Any]], dict[int, dict[str, Any]]]:
    """
    Interstitial step to process raw backbone graph data from core.py.
    Calculates segment geometry (length, incline) using simple linear depth_m.
    Passes along feature flags generated by core.py.
    Adds calculated geometry to the child node's data dict.

    Args:
        backbone_data: The dictionary loaded from CaveGenerator.to_json(),
                       containing 'nodes' list (potentially with 'feature' keys).

    Returns:
        tuple containing:
        - augmented_nodes (list[dict]): A copy of the nodes list, with added
            segment geometry keys where applicable (flags are passed through).
        - augmented_node_map (dict[int, dict]): A map from node ID to the
            corresponding augmented node dictionary.
    """
    if "nodes" not in backbone_data:
        print("Warning: 'nodes' key not found in backbone_data.")
        return [], {}

    def is_valid_int(value: object) -> bool:
        return isinstance(value, int) and not isinstance(value, bool)

    def is_valid_number(value: object) -> bool:
        return isinstance(value, (int, float)) and not isinstance(value, bool)

    def reset_geometry_fields(node: dict[str, Any]) -> None:
        node["segment_length_xy"] = 0.0
        node["segment_incline_rate"] = 0.0
        node["segment_delta_depth_m"] = 0.0
        node["bearing_deg"] = 0.0

    def validate_id(value: object) -> list[str]:
        if value is None:
            return ["Missing id."]
        if not is_valid_int(value):
            return [f"Invalid id value: {value!r}."]
        return []

    def validate_parent_id(value: object) -> list[str]:
        if value is None:
            return ["Missing parent_id."]
        if not is_valid_int(value):
            return [f"Invalid parent_id value: {value!r}."]
        return []

    def validate_coordinate(label: str, value: object) -> list[str]:
        if value is None or not is_valid_number(value):
            return [f"Invalid {label} value: {value!r}."]
        return []

    def normalize_children_ids(value: object) -> dict[str, Any]:
        if value is None:
            return {"normalized": [], "errors": []}
        if not isinstance(value, list):
            return {
                "normalized": [],
                "errors": [f"Invalid children_ids value: {value!r}."],
            }

        normalized = [child for child in value if is_valid_int(child)]
        if len(normalized) != len(value):
            return {
                "normalized": normalized,
                "errors": ["Invalid child id(s) in children_ids."],
            }
        return {"normalized": normalized, "errors": []}

    # Create shallow copies to avoid mutating the input without deep-copy cost.
    # Node dictionaries only contain primitive fields + children_ids list, which we
    # do not mutate during processing.
    nodes_list = [node.copy() for node in backbone_data["nodes"]]

    df = pl.DataFrame(nodes_list)
    for required_column in ("id", "parent_id", "x", "y", "children_ids"):
        if required_column not in df.columns:
            df = df.with_columns(pl.lit(None).alias(required_column))

    validation_schema = pl.Struct(
        [
            pl.Field("normalized", pl.List(pl.Int64)),
            pl.Field("errors", pl.List(pl.Utf8)),
        ]
    )
    df = df.with_columns(
        pl.col("id")
        .map_elements(validate_id, return_dtype=pl.List(pl.Utf8))
        .alias("id_errors"),
        pl.col("parent_id")
        .map_elements(validate_parent_id, return_dtype=pl.List(pl.Utf8))
        .alias("parent_id_errors"),
        pl.col("x")
        .map_elements(
            lambda value: validate_coordinate("x", value),
            return_dtype=pl.List(pl.Utf8),
        )
        .alias("x_errors"),
        pl.col("y")
        .map_elements(
            lambda value: validate_coordinate("y", value),
            return_dtype=pl.List(pl.Utf8),
        )
        .alias("y_errors"),
        pl.col("children_ids")
        .map_elements(normalize_children_ids, return_dtype=validation_schema)
        .alias("children_validation"),
    ).with_columns(
        pl.col("parent_id")
        .map_elements(
            lambda value: value if is_valid_int(value) else None,
            return_dtype=pl.Int64,
        )
        .alias("parent_id"),
    )

    df = df.with_columns(
        pl.col("children_validation").struct.field("normalized").alias("children_ids"),
        pl.col("children_validation").struct.field("errors").alias("children_errors"),
    ).with_columns(
        pl.concat_list(
            "id_errors",
            "parent_id_errors",
            "x_errors",
            "y_errors",
            "children_errors",
        ).alias("processing_errors")
    ).drop(
        "id_errors",
        "parent_id_errors",
        "x_errors",
        "y_errors",
        "children_validation",
        "children_errors",
    )

    nodes_list = df.to_dicts()
    valid_nodes = [n for n in nodes_list if is_valid_int(n.get("id"))]
    node_map = {n["id"]: n for n in valid_nodes}

    print(f"Processor: Calculating geometry for {len(nodes_list)} nodes...")

    # Iterate through the copied nodes to calculate segment geometry
    for node_data in nodes_list:
        if not is_valid_int(node_data.get("id")):
            reset_geometry_fields(node_data)
            continue

        if not is_valid_number(node_data.get("x")) or not is_valid_number(
            node_data.get("y")
        ):
            reset_geometry_fields(node_data)
            continue

        parent_id = node_data.get("parent_id")

        # Skip root or nodes with missing/invalid parents
        if parent_id is None or parent_id not in node_map:
            # Add default segment values for root if needed downstream?
            reset_geometry_fields(node_data)
            continue

        parent_data = node_map[parent_id]
        if not is_valid_number(parent_data.get("x")) or not is_valid_number(
            parent_data.get("y")
        ):
            reset_geometry_fields(node_data)
            continue

        # --- Calculate Segment Geometry ---
        delta_x = node_data["x"] - parent_data["x"]
        delta_y = node_data["y"] - parent_data["y"]
        segment_length_xy = np.hypot(delta_x, delta_y)

        # Use the simple 'depth_m' calculated by core.py
        delta_depth_m = node_data.get("depth_m", 0.0) - parent_data.get("depth_m", 0.0)

        incline_rate = 0.0
        if segment_length_xy < 0.01:  # Avoid division by zero
            # Handle vertical segments if needed (e.g., assign large incline)
            # However, incline rate isn't very meaningful here if core.py flagged it.
            # Let's keep it simple.
            pass
        else:
            incline_rate = delta_depth_m / segment_length_xy

        # Add calculated geometry to the *child* node's dictionary
        node_data["segment_length_xy"] = round(segment_length_xy, 2)
        node_data["segment_incline_rate"] = round(incline_rate, 2)
        node_data["segment_delta_depth_m"] = round(delta_depth_m, 2)
        node_data["bearing_deg"] = round(
            math.degrees(math.atan2(delta_y, delta_x)), 2
        )

        # --- Flagging is NO LONGER done here ---
        # Feature flags ('cliff_edge', 'shaft_opening') are assumed to be
        # already present in the parent_data if generated by core.py
        # The copied dicts ensure flags are carried over.

    def classify_node_type(parent_present: bool, degree: int) -> str:
        if not parent_present:
            return "root"
        if degree <= 1:
            return "leaf"
        if degree == 2:
            return "corridor"
        return "junction"

    def compute_flow_metrics(
        nodes: list[dict[str, Any]], node_lookup: dict[int, dict[str, Any]]
    ) -> None:
        flow_next_lookup: dict[int, int] = {}
        flow_distance_cache: dict[int, float] = {}

        for node in nodes:
            children_ids = node.get("children_ids") or []
            if not children_ids:
                node["flow_next_id"] = None
                flow_next_lookup[node["id"]] = None
                continue

            child_candidates = [
                node_lookup[child_id]
                for child_id in children_ids
                if child_id in node_lookup
            ]
            if not child_candidates:
                node["flow_next_id"] = None
                flow_next_lookup[node["id"]] = None
                continue

            next_node = min(child_candidates, key=lambda child: child.get("depth_m", 0.0))
            if next_node.get("depth_m", 0.0) >= node.get("depth_m", 0.0):
                node["flow_next_id"] = None
                flow_next_lookup[node["id"]] = None
            else:
                node["flow_next_id"] = next_node["id"]
                flow_next_lookup[node["id"]] = next_node["id"]

        def compute_flow_distance(node_id: int, visited: set[int]) -> float:
            if node_id in flow_distance_cache:
                return flow_distance_cache[node_id]
            if node_id in visited:
                flow_distance_cache[node_id] = 0.0
                return 0.0
            visited.add(node_id)

            next_id = flow_next_lookup.get(node_id)
            if next_id is None or next_id not in node_lookup:
                flow_distance_cache[node_id] = 0.0
                return 0.0

            next_node = node_lookup[next_id]
            segment_length = next_node.get("segment_length_xy", 0.0)
            total_distance = segment_length + compute_flow_distance(next_id, visited)
            flow_distance_cache[node_id] = total_distance
            return total_distance

        for node in nodes:
            node["flow_distance_m"] = round(
                compute_flow_distance(node["id"], set()), 2
            )

        accumulation = {node["id"]: 1 for node in nodes}
        nodes_by_depth = sorted(
            nodes, key=lambda n: n.get("depth_m", 0.0), reverse=True
        )
        for node in nodes_by_depth:
            next_id = flow_next_lookup.get(node["id"])
            if next_id is None or next_id not in accumulation:
                continue
            accumulation[next_id] += accumulation[node["id"]]

        for node in nodes:
            node["flow_accumulation_n"] = accumulation.get(node["id"], 1)

    path_length_cache: dict[int, float] = {}
    path_depth_cache: dict[int, int] = {}

    def compute_path_info(node_id: int) -> tuple[float, int]:
        if node_id in path_length_cache and node_id in path_depth_cache:
            return path_length_cache[node_id], path_depth_cache[node_id]

        node_data = node_map[node_id]
        parent_id = node_data.get("parent_id")
        if parent_id is None or parent_id not in node_map:
            path_length_cache[node_id] = 0.0
            path_depth_cache[node_id] = 0
            return 0.0, 0

        parent_length, parent_depth = compute_path_info(parent_id)
        segment_length = node_data.get("segment_length_xy", 0.0)
        total_length = parent_length + segment_length
        total_depth = parent_depth + 1
        path_length_cache[node_id] = total_length
        path_depth_cache[node_id] = total_depth
        return total_length, total_depth

    for node_data in valid_nodes:
        parent_id = node_data.get("parent_id")
        parent_present = parent_id is not None and parent_id in node_map
        children_count = len(node_data.get("children_ids") or [])
        degree = children_count + (1 if parent_present else 0)
        node_data["degree"] = degree
        node_data["node_type"] = classify_node_type(parent_present, degree)
        path_length, path_depth = compute_path_info(node_data["id"])
        node_data["path_length_from_root"] = round(path_length, 2)
        node_data["path_depth"] = path_depth

    compute_flow_metrics(valid_nodes, node_map)

    # Log counts of flags received from core.py
    cliff_count = sum(1 for n in nodes_list if n.get("feature") == "cliff_edge")
    shaft_count = sum(1 for n in nodes_list if n.get("feature") == "shaft_opening")
    print(
        f"Processor: Found {cliff_count} cliff edges, {shaft_count} shaft openings (generated by core)."
    )
    print("Processor: Geometry calculation complete.")

    return nodes_list, node_map


# --- Example Integration Snippet (if run directly for testing) ---
if __name__ == "__main__":
    import json

    # Assumes core.py generated 'generated_cave_contextual.json' or similar
    INPUT_JSON_FILE = "generated_cave_contextual.json"
    OUTPUT_PROCESSED_FILE = "processed_cave_data.json"

    try:
        with open(INPUT_JSON_FILE, "r") as f:
            raw_backbone_data = json.load(f)
        print(
            f"Loaded {len(raw_backbone_data['nodes'])} raw nodes from {INPUT_JSON_FILE}"
        )

        print("\n--- Running Interstitial Processing (Geometry Calculation Only) ---")
        augmented_nodes, augmented_node_map = process_backbone_graph(raw_backbone_data)

        # --- Optional: Save the augmented data ---
        output_data = {
            "nodes": augmented_nodes,
            "generation_settings": raw_backbone_data.get("generation_settings", {}),
        }
        with open(OUTPUT_PROCESSED_FILE, "w") as f:
            json.dump(output_data, f, indent=2)
        print(f"\nAugmented data saved to {OUTPUT_PROCESSED_FILE}")

        # Example: Check augmentation on a node known to have children
        example_parent_id = 3  # Example ID
        if example_parent_id in augmented_node_map:
            parent_node_example = augmented_node_map[example_parent_id]
            print(f"\nAugmented data for node {example_parent_id}:")
            print(parent_node_example)
            if parent_node_example.get("children_ids"):
                child_id = parent_node_example["children_ids"][0]
                if child_id in augmented_node_map:
                    print(f"\nAugmented data for its child node {child_id}:")
                    print(augmented_node_map[child_id])

    except FileNotFoundError:
        print(f"Error: Input file '{INPUT_JSON_FILE}' not found.")
        print("Please generate it by running the updated core.py first.")
    except Exception as e:
        print(f"An error occurred: {e}")
        import traceback

        traceback.print_exc()
