# Dungeon/processor.py

from typing import Dict, List, Tuple

import math

import numpy as np

# --- Constants (Ensure these are consistent with shaper.py if needed) ---
GRID_RESOLUTION = 1.0  # meters per grid cell

# --- (Heuristic Thresholds are NO LONGER NEEDED here) ---


def process_backbone_graph(backbone_data: Dict) -> Tuple[List[Dict], Dict[int, Dict]]:
    """
    Interstitial step to process raw backbone graph data from core.py.
    Calculates segment geometry (length, incline) using simple linear depth_m.
    Passes along feature flags generated by core.py.
    Adds calculated geometry to the child node's data dict.

    Args:
        backbone_data: The dictionary loaded from CaveGenerator.to_json(),
                       containing 'nodes' list (potentially with 'feature' keys).

    Returns:
        Tuple containing:
        - augmented_nodes (List[Dict]): A copy of the nodes list, with added
            segment geometry keys where applicable (flags are passed through).
        - augmented_node_map (Dict[int, Dict]): A map from node ID to the
            corresponding augmented node dictionary.
    """
    if "nodes" not in backbone_data:
        print("Warning: 'nodes' key not found in backbone_data.")
        return [], {}

    def is_valid_int(value: object) -> bool:
        return isinstance(value, int) and not isinstance(value, bool)

    def is_valid_number(value: object) -> bool:
        return isinstance(value, (int, float)) and not isinstance(value, bool)

    def add_processing_error(node: Dict, message: str) -> None:
        node.setdefault("processing_errors", []).append(message)

    # Create shallow copies to avoid mutating the input without deep-copy cost.
    # Node dictionaries only contain primitive fields + children_ids list, which we
    # do not mutate during processing.
    nodes_list = [node.copy() for node in backbone_data["nodes"]]

    for node_data in nodes_list:
        if "id" not in node_data:
            add_processing_error(node_data, "Missing id.")
        elif not is_valid_int(node_data.get("id")):
            add_processing_error(
                node_data, f"Invalid id value: {node_data.get('id')!r}."
            )

        if "parent_id" not in node_data:
            add_processing_error(node_data, "Missing parent_id.")
            node_data["parent_id"] = None
        else:
            parent_id_value = node_data.get("parent_id")
            if parent_id_value is not None and not is_valid_int(parent_id_value):
                add_processing_error(
                    node_data,
                    f"Invalid parent_id value: {node_data.get('parent_id')!r}.",
                )
                node_data["parent_id"] = None

        if "x" not in node_data or not is_valid_number(node_data.get("x")):
            add_processing_error(node_data, f"Invalid x value: {node_data.get('x')!r}.")
        if "y" not in node_data or not is_valid_number(node_data.get("y")):
            add_processing_error(node_data, f"Invalid y value: {node_data.get('y')!r}.")

        if "children_ids" not in node_data or node_data.get("children_ids") is None:
            node_data["children_ids"] = []
        elif not isinstance(node_data.get("children_ids"), list):
            add_processing_error(
                node_data,
                f"Invalid children_ids value: {node_data.get('children_ids')!r}.",
            )
            node_data["children_ids"] = []
        else:
            normalized_children: List[int] = []
            for child_id in node_data.get("children_ids", []):
                if is_valid_int(child_id):
                    normalized_children.append(child_id)
                else:
                    add_processing_error(
                        node_data,
                        f"Invalid child id in children_ids: {child_id!r}.",
                    )
            node_data["children_ids"] = normalized_children

    valid_nodes = [n for n in nodes_list if is_valid_int(n.get("id"))]
    node_map = {n["id"]: n for n in valid_nodes}

    print(f"Processor: Calculating geometry for {len(nodes_list)} nodes...")

    # Iterate through the copied nodes to calculate segment geometry
    for node_data in nodes_list:
        if not is_valid_int(node_data.get("id")):
            node_data["segment_length_xy"] = 0.0
            node_data["segment_incline_rate"] = 0.0
            node_data["segment_delta_depth_m"] = 0.0
            node_data["bearing_deg"] = 0.0
            continue

        if not is_valid_number(node_data.get("x")) or not is_valid_number(
            node_data.get("y")
        ):
            node_data["segment_length_xy"] = 0.0
            node_data["segment_incline_rate"] = 0.0
            node_data["segment_delta_depth_m"] = 0.0
            node_data["bearing_deg"] = 0.0
            continue

        parent_id = node_data.get("parent_id")

        # Skip root or nodes with missing/invalid parents
        if parent_id is None or parent_id not in node_map:
            # Add default segment values for root if needed downstream?
            node_data["segment_length_xy"] = 0.0
            node_data["segment_incline_rate"] = 0.0
            node_data["segment_delta_depth_m"] = 0.0
            node_data["bearing_deg"] = 0.0
            continue

        parent_data = node_map[parent_id]
        if not is_valid_number(parent_data.get("x")) or not is_valid_number(
            parent_data.get("y")
        ):
            node_data["segment_length_xy"] = 0.0
            node_data["segment_incline_rate"] = 0.0
            node_data["segment_delta_depth_m"] = 0.0
            node_data["bearing_deg"] = 0.0
            continue

        # --- Calculate Segment Geometry ---
        delta_x = node_data["x"] - parent_data["x"]
        delta_y = node_data["y"] - parent_data["y"]
        segment_length_xy = np.hypot(delta_x, delta_y)

        # Use the simple 'depth_m' calculated by core.py
        delta_depth_m = node_data.get("depth_m", 0.0) - parent_data.get("depth_m", 0.0)

        incline_rate = 0.0
        if segment_length_xy < 0.01:  # Avoid division by zero
            # Handle vertical segments if needed (e.g., assign large incline)
            # However, incline rate isn't very meaningful here if core.py flagged it.
            # Let's keep it simple.
            pass
        else:
            incline_rate = delta_depth_m / segment_length_xy

        # Add calculated geometry to the *child* node's dictionary
        node_data["segment_length_xy"] = round(segment_length_xy, 2)
        node_data["segment_incline_rate"] = round(incline_rate, 2)
        node_data["segment_delta_depth_m"] = round(delta_depth_m, 2)
        node_data["bearing_deg"] = round(
            math.degrees(math.atan2(delta_y, delta_x)), 2
        )

        # --- Flagging is NO LONGER done here ---
        # Feature flags ('cliff_edge', 'shaft_opening') are assumed to be
        # already present in the parent_data if generated by core.py
        # The copied dicts ensure flags are carried over.

    def classify_node_type(parent_present: bool, degree: int) -> str:
        if not parent_present:
            return "root"
        if degree <= 1:
            return "leaf"
        if degree == 2:
            return "corridor"
        return "junction"

    def compute_flow_metrics(nodes: List[Dict], node_lookup: Dict[int, Dict]) -> None:
        flow_next_lookup: Dict[int, int] = {}
        flow_distance_cache: Dict[int, float] = {}

        for node in nodes:
            children_ids = node.get("children_ids") or []
            if not children_ids:
                node["flow_next_id"] = None
                flow_next_lookup[node["id"]] = None
                continue

            child_candidates = [
                node_lookup[child_id]
                for child_id in children_ids
                if child_id in node_lookup
            ]
            if not child_candidates:
                node["flow_next_id"] = None
                flow_next_lookup[node["id"]] = None
                continue

            next_node = min(child_candidates, key=lambda child: child.get("depth_m", 0.0))
            if next_node.get("depth_m", 0.0) >= node.get("depth_m", 0.0):
                node["flow_next_id"] = None
                flow_next_lookup[node["id"]] = None
            else:
                node["flow_next_id"] = next_node["id"]
                flow_next_lookup[node["id"]] = next_node["id"]

        def compute_flow_distance(node_id: int, visited: set) -> float:
            if node_id in flow_distance_cache:
                return flow_distance_cache[node_id]
            if node_id in visited:
                flow_distance_cache[node_id] = 0.0
                return 0.0
            visited.add(node_id)

            next_id = flow_next_lookup.get(node_id)
            if next_id is None or next_id not in node_lookup:
                flow_distance_cache[node_id] = 0.0
                return 0.0

            next_node = node_lookup[next_id]
            segment_length = next_node.get("segment_length_xy", 0.0)
            total_distance = segment_length + compute_flow_distance(next_id, visited)
            flow_distance_cache[node_id] = total_distance
            return total_distance

        for node in nodes:
            node["flow_distance_m"] = round(
                compute_flow_distance(node["id"], set()), 2
            )

        accumulation = {node["id"]: 1 for node in nodes}
        nodes_by_depth = sorted(
            nodes, key=lambda n: n.get("depth_m", 0.0), reverse=True
        )
        for node in nodes_by_depth:
            next_id = flow_next_lookup.get(node["id"])
            if next_id is None or next_id not in accumulation:
                continue
            accumulation[next_id] += accumulation[node["id"]]

        for node in nodes:
            node["flow_accumulation_n"] = accumulation.get(node["id"], 1)

    path_length_cache: Dict[int, float] = {}
    path_depth_cache: Dict[int, int] = {}

    def compute_path_info(node_id: int) -> Tuple[float, int]:
        if node_id in path_length_cache and node_id in path_depth_cache:
            return path_length_cache[node_id], path_depth_cache[node_id]

        node_data = node_map[node_id]
        parent_id = node_data.get("parent_id")
        if parent_id is None or parent_id not in node_map:
            path_length_cache[node_id] = 0.0
            path_depth_cache[node_id] = 0
            return 0.0, 0

        parent_length, parent_depth = compute_path_info(parent_id)
        segment_length = node_data.get("segment_length_xy", 0.0)
        total_length = parent_length + segment_length
        total_depth = parent_depth + 1
        path_length_cache[node_id] = total_length
        path_depth_cache[node_id] = total_depth
        return total_length, total_depth

    for node_data in valid_nodes:
        parent_id = node_data.get("parent_id")
        parent_present = parent_id is not None and parent_id in node_map
        children_count = len(node_data.get("children_ids") or [])
        degree = children_count + (1 if parent_present else 0)
        node_data["degree"] = degree
        node_data["node_type"] = classify_node_type(parent_present, degree)
        path_length, path_depth = compute_path_info(node_data["id"])
        node_data["path_length_from_root"] = round(path_length, 2)
        node_data["path_depth"] = path_depth

    compute_flow_metrics(valid_nodes, node_map)

    # Log counts of flags received from core.py
    cliff_count = sum(1 for n in nodes_list if n.get("feature") == "cliff_edge")
    shaft_count = sum(1 for n in nodes_list if n.get("feature") == "shaft_opening")
    print(
        f"Processor: Found {cliff_count} cliff edges, {shaft_count} shaft openings (generated by core)."
    )
    print("Processor: Geometry calculation complete.")

    return nodes_list, node_map


# --- Example Integration Snippet (if run directly for testing) ---
if __name__ == "__main__":
    import json

    # Assumes core.py generated 'generated_cave_contextual.json' or similar
    INPUT_JSON_FILE = "generated_cave_contextual.json"
    OUTPUT_PROCESSED_FILE = "processed_cave_data.json"

    try:
        with open(INPUT_JSON_FILE, "r") as f:
            raw_backbone_data = json.load(f)
        print(
            f"Loaded {len(raw_backbone_data['nodes'])} raw nodes from {INPUT_JSON_FILE}"
        )

        print("\n--- Running Interstitial Processing (Geometry Calculation Only) ---")
        augmented_nodes, augmented_node_map = process_backbone_graph(raw_backbone_data)

        # --- Optional: Save the augmented data ---
        output_data = {
            "nodes": augmented_nodes,
            "generation_settings": raw_backbone_data.get("generation_settings", {}),
        }
        with open(OUTPUT_PROCESSED_FILE, "w") as f:
            json.dump(output_data, f, indent=2)
        print(f"\nAugmented data saved to {OUTPUT_PROCESSED_FILE}")

        # Example: Check augmentation on a node known to have children
        example_parent_id = 3  # Example ID
        if example_parent_id in augmented_node_map:
            parent_node_example = augmented_node_map[example_parent_id]
            print(f"\nAugmented data for node {example_parent_id}:")
            print(parent_node_example)
            if parent_node_example.get("children_ids"):
                child_id = parent_node_example["children_ids"][0]
                if child_id in augmented_node_map:
                    print(f"\nAugmented data for its child node {child_id}:")
                    print(augmented_node_map[child_id])

    except FileNotFoundError:
        print(f"Error: Input file '{INPUT_JSON_FILE}' not found.")
        print("Please generate it by running the updated core.py first.")
    except Exception as e:
        print(f"An error occurred: {e}")
        import traceback

        traceback.print_exc()
