#!/usr/bin/env python3
"""Sync the canonical LLM policy to all agent-specific copies.

Reads ``docs/LLM_CRITICAL_RULES.md`` and writes it (with a header) into
each target location so every code-assist agent has an up-to-date local copy.

Usage::

    python scripts/sync_llm_policy.py          # write targets
    python scripts/sync_llm_policy.py --check   # CI mode: fail if out of date
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Final

REPO_ROOT: Path = Path(__file__).resolve().parent.parent
CANONICAL: Path = REPO_ROOT / "docs" / "LLM_CRITICAL_RULES.md"

HEADER: str = (
    "<!-- AUTOGENERATED COPY — DO NOT EDIT.\n"
    "     Canonical source: docs/LLM_CRITICAL_RULES.md\n"
    "     Regenerate with: python scripts/sync_llm_policy.py -->\n\n"
)

TARGETS: Final[Tuple[Path, ...]] = (
    REPO_ROOT / ".codex" / "AGENTS.md",
    REPO_ROOT / ".gemini" / "styleguide.md",
    REPO_ROOT / "CLAUDE.md",
)


def sync(*, check_only: bool = False) -> bool:
    """Write (or verify) all targets. Returns True if all are up-to-date."""
    canon_text: str = CANONICAL.read_text(encoding="utf-8")
    expected: str = HEADER + canon_text
    all_ok: bool = True

    for target in TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)

        if check_only:
            if not target.exists():
                print(f"MISSING: {target.relative_to(REPO_ROOT)}")
                all_ok = False
                continue
            current: str = target.read_text(encoding="utf-8")
            if current != expected:
                print(f"OUT OF DATE: {target.relative_to(REPO_ROOT)}")
                all_ok = False
        else:
            target.write_text(expected, encoding="utf-8")
            print(f"  wrote {target.relative_to(REPO_ROOT)}")

    return all_ok


def main() -> None:
    check_only: bool = "--check" in sys.argv
    ok: bool = sync(check_only=check_only)

    if check_only and not ok:
        print(
            "\nRun `python scripts/sync_llm_policy.py` to regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)

    if not check_only:
        print("LLM policy synced.")


if __name__ == "__main__":
    main()
