#!/usr/bin/env python3
"""Sync the canonical LLM policy to all agent-specific copies.

Reads ``docs/LLM_CRITICAL_RULES.md`` and writes it (with generated headers) into
all target locations so every code-assist agent has an up-to-date local copy.

Usage::

    python scripts/sync_llm_policy.py          # write targets
    python scripts/sync_llm_policy.py --check  # CI mode: fail if out of date
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Final

REPO_ROOT: Final[Path] = Path(__file__).resolve().parent.parent
CANONICAL: Final[Path] = REPO_ROOT / "docs" / "LLM_CRITICAL_RULES.md"

HEADER: Final[str] = (
    "<!-- AUTOGENERATED COPY — DO NOT EDIT.\n"
    "     Canonical source: docs/LLM_CRITICAL_RULES.md\n"
    "     Regenerate with: python scripts/sync_llm_policy.py -->\n\n"
)

CODEX_EXECUTION_REMINDER: Final[
    str
] = """## Codex execution reminder

Before editing code, read the repository instruction file that applies to the edited path.

For this repository, static typing is mandatory.

Do not complete a code change unless new and modified Python code follows these rules:

* Fully typed function and method signatures.
* `-> None` on void functions.
* `X | None`, never `Optional[X]`.
* `list[str]`, `dict[str, int]`, `tuple[int, ...]`, `set[str]`; never `typing.List`, `typing.Dict`, `typing.Tuple`, or `typing.Set`.
* No avoidable `Any`.
* Explicit types for empty collections, constants, module globals, and class attributes.
* No new or expanded `ignore_errors = true` mypy overrides.

Run:

```bash
python -m black .
python -m ruff check .
python -m mypy .
```

If the changed module is hidden behind a mypy `ignore_errors = true` override, do not treat a passing `mypy .` result as proof that the changed code is correctly typed. Make the edited code strict-typed anyway.

---

"""

TARGET_PREFIXES: Final[dict[Path, str]] = {
    REPO_ROOT / "AGENTS.md": "",
    REPO_ROOT / ".codex" / "AGENTS.md": CODEX_EXECUTION_REMINDER,
    REPO_ROOT / ".github" / "copilot-instructions.md": "",
    REPO_ROOT / ".gemini" / "styleguide.md": "",
    REPO_ROOT / "CLAUDE.md": "",
}


def build_expected_text(prefix: str, canon_text: str) -> str:
    """Return generated file content for one target."""
    if prefix:
        return HEADER + prefix + canon_text
    return HEADER + canon_text


def sync(*, check_only: bool = False) -> bool:
    """Write (or verify) all targets and return True when all are up-to-date."""
    canon_text: str = CANONICAL.read_text(encoding="utf-8")
    all_ok: bool = True

    for target, prefix in TARGET_PREFIXES.items():
        expected: str = build_expected_text(prefix, canon_text)
        target.parent.mkdir(parents=True, exist_ok=True)

        if check_only:
            if not target.exists():
                print(f"MISSING: {target.relative_to(REPO_ROOT)}")
                all_ok = False
                continue
            current: str = target.read_text(encoding="utf-8")
            if current != expected:
                print(f"OUT OF DATE: {target.relative_to(REPO_ROOT)}")
                all_ok = False
            continue

        target.write_text(expected, encoding="utf-8")
        print(f"  wrote {target.relative_to(REPO_ROOT)}")

    return all_ok


def main() -> None:
    """Entrypoint for CLI execution."""
    check_only: bool = "--check" in sys.argv
    ok: bool = sync(check_only=check_only)

    if check_only and not ok:
        print(
            "\nRun `python scripts/sync_llm_policy.py` to regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)

    if not check_only:
        print("LLM policy synced.")


if __name__ == "__main__":
    main()
